[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=50MB

[program:gunicorn]
command=/usr/local/bin/gunicorn -b 0.0.0.0:5000 -w 2 --timeout 120 app:app
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn.err.log
stdout_logfile=/var/log/gunicorn.out.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
